#cloud-config
hostname: apache2
users:
  - name: debian
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    shell: /bin/bash
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHiYl8Co8WopWUl0IpwkIaGSJvJ5E18jojHVrxQQrGK/ sjnezsrez@gmail.com
chpasswd:
  expire: False
  users:
    - name: debian
      password: asdasd
      type: text


