network:
  version: 2
  ethernets:
    ens3: 
      dhcp4: false
      addresses: ["192.168.10.11/24"]
      gateway4: 192.168.10.1
      nameservers:
        addresses:
          - 192.168.10.1
    ens4: 
      dhcp4: false
      addresses: ["192.168.100.100/24"]
